coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flags:
  go:
    paths:
      - apps/api/
    carryforward: true
  rails:
    paths:
      - apps/dashboard/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
