# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.8

# ── PDF generator ─────────────────────────────────────────────────────────────
# `scripts` is passed as an additional build context from docker-compose so this
# stage has no impact on the dashboard's own layer cache.
FROM node:20-alpine AS pdf-builder

WORKDIR /build
COPY --from=scripts package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --from=scripts . .
# Script resolves OUT_DIR relative to __dirname: ../apps/dashboard/public/documents
RUN node generate-docs.mjs

# ── Ruby base ─────────────────────────────────────────────────────────────────
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

WORKDIR /rails

RUN --mount=type=cache,id=apt-base,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=apt-base-lib,target=/var/lib/apt,sharing=locked \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so

ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development" \
    LD_PRELOAD="/usr/local/lib/libjemalloc.so"

FROM base AS build

RUN --mount=type=cache,id=apt-build,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=apt-build-lib,target=/var/lib/apt,sharing=locked \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config

COPY Gemfile Gemfile.lock ./

RUN --mount=type=cache,id=bundler,target=/usr/local/bundle/cache \
    bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile -j 1 --gemfile

COPY . .

# Inject PDFs generated by the pdf-builder stage (OUT_DIR = /apps/dashboard/public/documents)
COPY --from=pdf-builder /apps/dashboard/public/documents ./public/documents

RUN bundle exec bootsnap precompile -j 1 app/ lib/

RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile

FROM base

RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash
USER 1000:1000

COPY --chown=rails:rails --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --chown=rails:rails --from=build /rails /rails

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 80
CMD ["./bin/thrust", "./bin/rails", "server"]
