# frozen_string_literal: true

class Dashboard::ApiKeysController < Dashboard::BaseController
  before_action :set_api_key, only: [ :regenerate, :revoke ]

  def index
    @api_keys = current_user.api_keys.order(created_at: :desc)
    @active_keys = @api_keys.active_keys
    @revoked_keys = @api_keys.revoked
  end

  def new
    @api_key = current_user.api_keys.build
  end

  def create
    @api_key = current_user.api_keys.build(api_key_params)

    if @api_key.save
      # The full key is only available once during creation
      @show_full_key = true
      flash.now[:notice] = t("dashboard.api_keys.flash.created")
      render :show_key
    else
      render :new, status: :unprocessable_entity
    end
  end

  def regenerate
    if @api_key.revoked_at.present?
      redirect_to dashboard_api_keys_path, alert: t("dashboard.api_keys.flash.cannot_regenerate_revoked")
      return
    end

    # Revoke old key
    @api_key.revoke!(reason: "Regenerated by user")

    # Create new key with same name
    @new_api_key = current_user.api_keys.create!(
      name: @api_key.name,
      environment: @api_key.environment
    )

    @show_full_key = true
    @api_key = @new_api_key
    flash.now[:notice] = t("dashboard.api_keys.flash.regenerated")
    render :show_key
  end

  def revoke
    if @api_key.revoke!(reason: "Revoked by user")
      redirect_to dashboard_api_keys_path, notice: t("dashboard.api_keys.flash.revoked")
    else
      redirect_to dashboard_api_keys_path, alert: t("dashboard.api_keys.flash.revoke_error")
    end
  end

  private

  def set_api_key
    @api_key = current_user.api_keys.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to dashboard_api_keys_path, alert: t("dashboard.api_keys.flash.not_found")
  end

  def api_key_params
    params.require(:api_key).permit(:name, :environment)
  end
end
