# frozen_string_literal: true

require "test_helper"

class Dashboard::ApiKeysControllerTest < ActionDispatch::IntegrationTest
  def setup
    @user = create_user(
      email: "test@example.com",
      password: "password123",
      password_confirmation: "password123"
    )

    @api_key = @user.api_keys.create!(
      name: "Test Key",
      environment: "live"
    )

    sign_in @user
  end

  test "index requires authentication" do
    sign_out @user
    get dashboard_api_keys_path

    assert_redirected_to new_user_session_path
  end

  test "index shows user's api keys" do
    get dashboard_api_keys_path

    assert_response :success
    assert_select "h1", text: /API Keys/i
  end

  test "new shows create key form" do
    get new_dashboard_api_key_path

    assert_response :success
    assert_select "form"
    assert_select "input[name='api_key[name]']"
    # Environment is a hidden field defaulting to live (no test environment)
    assert_select "input[type='hidden'][name='api_key[environment]'][value='live']"
  end

  test "create generates new api key" do
    assert_difference "ApiKey.count", 1 do
      post dashboard_api_keys_path, params: {
        api_key: {
          name: "New Key",
          environment: "live"
        }
      }
    end

    # Controller renders show_key template instead of redirecting
    assert_response :success
    # show_key template has h2 (success message) and h3 (key name), but no h1
    assert_select "h2", text: /API Key Created Successfully/i

    new_key = ApiKey.last
    assert_equal "New Key", new_key.name
    assert_equal "live", new_key.environment
    assert_equal @user, new_key.user
    assert_not_nil new_key.key_hash
    assert_not_nil new_key.key_prefix
    assert new_key.key_prefix.start_with?("requiem_")
  end

  test "create requires name" do
    assert_no_difference "ApiKey.count" do
      post dashboard_api_keys_path, params: {
        api_key: {
          name: "",
          environment: "live"
        }
      }
    end

    assert_response :unprocessable_entity
  end

  test "regenerate revokes old key and creates new one" do
    old_key_prefix = @api_key.key_prefix

    assert_difference "ApiKey.count", 1 do
      post regenerate_dashboard_api_key_path(@api_key)
    end

    @api_key.reload
    assert_not_nil @api_key.revoked_at
    assert_equal "Regenerated by user", @api_key.revoked_reason

    new_key = ApiKey.order(created_at: :desc).first
    assert_equal @api_key.name, new_key.name
    assert_equal @api_key.environment, new_key.environment
    assert_not_equal old_key_prefix, new_key.key_prefix
  end

  test "regenerate requires own key" do
    other_user = create_user(email: "other@example.com")

    other_key = other_user.api_keys.create!(
      name: "Other Key",
      environment: "live"
    )

    # Controller rescues RecordNotFound and redirects with alert
    post regenerate_dashboard_api_key_path(other_key)

    assert_redirected_to dashboard_api_keys_path
    assert_equal "API key not found.", flash[:alert]
  end

  test "revoke marks key as revoked" do
    delete revoke_dashboard_api_key_path(@api_key)

    @api_key.reload
    assert_not_nil @api_key.revoked_at
    assert_equal "Revoked by user", @api_key.revoked_reason

    assert_redirected_to dashboard_api_keys_path
  end

  test "cannot regenerate already revoked key" do
    @api_key.revoke!(reason: "Test")

    post regenerate_dashboard_api_key_path(@api_key)

    assert_redirected_to dashboard_api_keys_path
    assert_equal "Cannot regenerate a revoked key. Please create a new one.", flash[:alert]
  end
end
